- hosts: localhost
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Create deployment directory
      file:
        path: /opt/petclinic
        state: directory
        mode: '0755'

    - name: Copy JAR file to deployment directory
      copy:
        src: /var/jenkins_home/workspace/spring-petclinic_main/target/spring-petclinic-3.2.0-SNAPSHOT.jar
        dest: /opt/petclinic/petclinic.jar
        mode: '0644'

    - name: Run Spring Petclinic application
      shell: java -jar /opt/petclinic/petclinic.jar --server.port=8081
      args:
        chdir: /opt/petclinic
        executable: /bin/bash