- hosts: prod
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes

  tasks:
    - name: copy the jar file to target host
      copy:
        src: ./target/spring-petclinic-2.4.2.jar
        dest: ./petclinic.jar
    - name: install openjdk11
      become: yes
      apt:
        name: openjdk-11-jre
        state: latest
        update_cache: yes
    - name: run the jar file
      shell: nohup java -jar petclinic.jar &
      args:
        executable: /bin/bash

  # tasks:
  #   - name: Update and upgrade apt packages
  #     apt:
  #       update_cache: yes
  #       upgrade: 'yes'

  #   - name: Install OpenJDK 11
  #     apt:
  #       name: openjdk-11-jdk
  #       state: present

  #   - name: Pull the latest Ubuntu image
  #     docker_image:
  #       name: ubuntu
  #       tag: 20.04
  #       source: pull
    
  #   - name: Create a container running Petclinic
  #     docker_container:
  #       name: petclinic
  #       image: ubuntu:20.04
  #       # command: >
  #       #   sh -c "
  #       #   apt update &&
  #       #   apt install -y openjdk-11-jre-headless &&
  #       #   wget -O petclinic.jar /var/jenkins_home/workspace/spring-petclinic_main/target/spring-petclinic-3.2.0-SNAPSHOT.jar &&
  #       #   java -jar petclinic.jar
  #       #   "
  #       ports:
  #         - "8080:8080"
  #       detached: yes
  #       state: started 
# - name: deploy one petclinic to one server
#   hosts: service




    # - name: Deploy Petclinic Application
    #   copy:
    #     src: /var/jenkins_home/workspace/spc_main/target/spring-petclinic-3.2.0-SNAPSHOT.jar
    #     dest: /opt/petclinic.jar
    # - name: Run Petclinic Application
    #   command: java -jar /opt/petclinic.jar --server.port=80
